const { User } = require("../models");

const userData = [
	{ id: 1, username: "odeason0", email: "apaddison0@myspace.com", password: "vK0u934X" },
	{ id: 2, username: "kvila1", email: "jgellett1@jiathis.com", password: "LWe4y7Ty" },
	{ id: 3, username: "vspringham2", email: "cfrodsam2@themeforest.net", password: "3MN6ua0" },
	{ id: 4, username: "rleadbitter3", email: "etroctor3@apache.org", password: "CAbySTJ2W" },
	{ id: 5, username: "kburgoyne4", email: "vjado4@tripod.com", password: "SmWPOP" },
	{ id: 6, username: "ptolson5", email: "askade5@nationalgeographic.com", password: "FAAshHvso" },
	{ id: 7, username: "dbrisse6", email: "mswede6@tripadvisor.com", password: "yRR2pS" },
	{ id: 8, username: "dmontez7", email: "wfreckelton7@sogou.com", password: "cNxb9Hr" },
	{ id: 9, username: "kspellacy8", email: "droux8@yellowbook.com", password: "UHkn7dHtb" },
	{ id: 10, username: "cengelbrecht9", email: "mlukas9@ifeng.com", password: "Qx9Gw2Cs9" },
	{ id: 11, username: "fwaldera", email: "esalwaya@ning.com", password: "d4iiDCX" },
	{ id: 12, username: "fdhillonb", email: "cwhitfieldb@gmpg.org", password: "6nHcFV8G6nE" },
	{ id: 13, username: "cboicec", email: "sproctorc@springer.com", password: "ZZDUKAE4p" },
	{ id: 14, username: "wlawleffd", email: "ctrytsmand@privacy.gov.au", password: "vCCNXTeeE" },
	{ id: 15, username: "nmckevitte", email: "jlowerye@yale.edu", password: "LFJviIvM" },
	{ id: 16, username: "jborsayf", email: "vbartosf@virginia.edu", password: "uJPhMbpNu7" },
	{ id: 17, username: "kairesg", email: "sambrusg@seesaa.net", password: "Fx2zT8y" },
	{ id: 18, username: "rbrookesbieh", email: "slagneauxh@exblog.jp", password: "FBvsRm" },
	{ id: 19, username: "lpilleyi", email: "alegalloi@surveymonkey.com", password: "wS0PLf0QQ" },
	{ id: 20, username: "kwilcockj", email: "kmacmasterj@mapquest.com", password: "EgKPwbqd1u" },
	{ id: 21, username: "vmcilraithk", email: "dorgelk@etsy.com", password: "8WJQOV" },
	{ id: 22, username: "lspringettl", email: "mpachecol@army.mil", password: "Binro4i8Mxl0" },
	{ id: 23, username: "ejessupm", email: "jpettisallm@live.com", password: "7afR9fR3" },
	{ id: 24, username: "wstormesn", email: "barmaln@ft.com", password: "WHmcD2JUs" },
	{ id: 25, username: "mfladeo", email: "ntozero@wunderground.com", password: "f10Km5kCZjb7" },
	{ id: 26, username: "zimmsp", email: "fidalep@de.vu", password: "dDpoYyVFH4wZ" },
	{ id: 27, username: "fnizetq", email: "jcripleq@who.int", password: "oxLpcY5" },
	{ id: 28, username: "mpreistr", email: "tinmanr@issuu.com", password: "XJ1cuJuD" },
	{ id: 29, username: "emaylours", email: "bkupiszs@imageshack.us", password: "Hfvq0AZ" },
	{ id: 30, username: "wscourgiet", email: "adrohant@toplist.cz", password: "0oTJ2VAd" },
	{ id: 31, username: "cewbachu", email: "tmaffiniu@people.com.cn", password: "8F53Ry15F8" },
	{ id: 32, username: "acoplestonev", email: "imckinneyv@goo.gl", password: "xi5B33PnY9" },
	{ id: 33, username: "jmannakeew", email: "fugoniw@nhs.uk", password: "bvb5jZ" },
	{ id: 34, username: "mdunnicox", email: "ccheshirx@toplist.cz", password: "LTyf4q5" },
	{ id: 35, username: "zpigramy", email: "dbernadey@sakura.ne.jp", password: "2XnjLIiTfm8" },
	{ id: 36, username: "cobingtonz", email: "mworthingz@icq.com", password: "OibNOJCIDyu" },
	{ id: 37, username: "gsimonin10", email: "eflowitt10@shareasale.com", password: "0FrS5xz33GK" },
	{ id: 38, username: "iplampeyn11", email: "dfronczak11@nbcnews.com", password: "KbWE5qLRwniw" },
	{ id: 39, username: "joregan12", email: "adaymont12@buzzfeed.com", password: "DycTVUD8agr2" },
	{ id: 40, username: "fforbear13", email: "atite13@noaa.gov", password: "4SB23Z" },
	{ id: 41, username: "cpiatek14", email: "rhanny14@google.cn", password: "Tta26uaC" },
	{ id: 42, username: "gfairbridge15", email: "bbamber15@wix.com", password: "blkcUhSN" },
	{ id: 43, username: "gmaykin16", email: "hortega16@ucoz.com", password: "xJP3kgk" },
	{ id: 44, username: "jmungan17", email: "hkinnon17@cpanel.net", password: "08oQWngO" },
	{ id: 45, username: "acordle18", email: "telleyne18@oaic.gov.au", password: "dmoM0BloJHrL" },
	{ id: 46, username: "bdives19", email: "eweafer19@loc.gov", password: "WFqQk7DAs" },
	{ id: 47, username: "qchastney1a", email: "mlindmark1a@so-net.ne.jp", password: "aVH54VmF" },
	{ id: 48, username: "molrenshaw1b", email: "mantoszewski1b@mapquest.com", password: "hgGpi59tw4" },
	{ id: 49, username: "amateescu1c", email: "aburnage1c@t.co", password: "d9DNfy" },
	{ id: 50, username: "cmangham1d", email: "lgothard1d@patch.com", password: "NMRF2k2HVNcT" },
];

const seedUsers = () => User.bulkCreate(userData);

module.exports = seedUsers;
