const { User } = require("../models");

const userData = [
	{ username: "mrizziello0", email: "bfattori0@deliciousdays.com", password: "dnGbQwAQ" },
	{ username: "jbrenston1", email: "dsalle1@answers.com", password: "klkUVM" },
	{ username: "mdungate2", email: "mwaddilow2@nih.gov", password: "sTzzt94v5EA" },
	{ username: "jwile3", email: "nmersh3@cargocollective.com", password: "NsfWiiv" },
	{ username: "awickersham4", email: "amunkley4@baidu.com", password: "vbYNgWFWl" },
	{ username: "mlloydwilliams5", email: "gpenkman5@shinystat.com", password: "42f69T6" },
	{ username: "paynsley6", email: "asealove6@skype.com", password: "dxgt61xf7nG" },
	{ username: "enesfield7", email: "rkliche7@globo.com", password: "3UQc8W4" },
	{ username: "iperford8", email: "leaddy8@ebay.co.uk", password: "oVyCRcR8k2b" },
	{ username: "ccordes9", email: "dfassbender9@xing.com", password: "xog1UK" },
	{ username: "kheavensa", email: "pchampleya@latimes.com", password: "wfO7Ya93K" },
	{ username: "drobertetb", email: "atomalinb@imgur.com", password: "RV1ZGm" },
	{ username: "cberlinc", email: "chamberstonc@unicef.org", password: "lIkcOSigG0" },
	{ username: "nbernadond", email: "bleggesd@stumbleupon.com", password: "DtqznBnNtOe" },
	{ username: "cudelle", email: "cmckinlaye@parallels.com", password: "dJjE9zPw" },
	{ username: "aimpeyf", email: "cwaitlandf@vinaora.com", password: "eVRJkJSuK3Qu" },
	{ username: "cmacauleyg", email: "abonnierg@gov.uk", password: "bNpHXN75ls7" },
	{ username: "dkensleyh", email: "dgadeauxh@google.ru", password: "8zEiVvoOu3M" },
	{ username: "mscopyni", email: "cgoodhalli@unesco.org", password: "9jTGRafL" },
	{ username: "pdunstonj", email: "zelfittj@umn.edu", password: "kAS6Wf" },
	{ username: "hmanochk", email: "wrichardk@wired.com", password: "cI3pyb51UNU" },
	{ username: "lcicchinellil", email: "tjandell@sakura.ne.jp", password: "4vkvMLVp4RVb" },
	{ username: "pgentlem", email: "cgauchierm@fastcompany.com", password: "4CqhqhWWXP" },
	{ username: "fvernyn", email: "tgarrityn@woothemes.com", password: "K1u1i4" },
	{ username: "wsafeo", email: "gfearensideo@ow.ly", password: "E5v4g3j" },
	{ username: "dogilviep", email: "wkenawayp@1688.com", password: "FX1d5DddlkVR" },
	{ username: "vbrentonq", email: "jmulgrewq@dailymail.co.uk", password: "TJ5KId" },
	{ username: "dmacgovernr", email: "dredittr@blinklist.com", password: "nHukpysDQ" },
	{ username: "mcoulstons", email: "sstibbss@edublogs.org", password: "tnYoXE1UvUu" },
	{ username: "ggouthiert", email: "wbullimoret@blinklist.com", password: "3bMwMOXv" },
	{ username: "svansaltsbergu", email: "pmartinau@disqus.com", password: "Nzdxk8k5sOjQ" },
	{ username: "rlemaryv", email: "krubinovitschv@bizjournals.com", password: "vy28uASZ9t" },
	{ username: "acandyw", email: "rrandlew@ebay.com", password: "n6KAOym1eyKQ" },
	{ username: "pblandenx", email: "bpavlovicx@nydailynews.com", password: "5HReMjF" },
	{ username: "lskillingsy", email: "dmcginlyy@sciencedirect.com", password: "TwO6l3vhcl9" },
	{ username: "kgoslandz", email: "dartinstallz@elegantthemes.com", password: "1BivbA5" },
	{ username: "cmccarney10", email: "mginn10@spiegel.de", password: "L5jF4A" },
	{ username: "sscarlan11", email: "btruin11@google.fr", password: "Q4YcRwIyHq" },
	{ username: "dsatterthwaite12", email: "apaule12@examiner.com", password: "hZU5ucbq2W" },
	{ username: "aschach13", email: "hgemmill13@google.fr", password: "0e7xwH19" },
	{ username: "bbowler14", email: "jchorley14@tamu.edu", password: "CnIjtvHEWH" },
	{ username: "lofihily15", email: "lreicharz15@europa.eu", password: "7Hcmo5dZNIAX" },
	{ username: "cmchirrie16", email: "mtarpey16@jigsy.com", password: "utJj0SEvwRa7" },
	{ username: "cjansson17", email: "ytownsley17@hhs.gov", password: "59BWk8e" },
	{ username: "mwilshire18", email: "cdesimoni18@creativecommons.org", password: "wld4g0DT3mo1" },
	{ username: "srubertelli19", email: "jchalloner19@goo.ne.jp", password: "tZcknFvdeEb" },
	{ username: "chadcroft1a", email: "tchallin1a@hud.gov", password: "1rVqIh7" },
	{ username: "araggitt1b", email: "srickardsson1b@rambler.ru", password: "imV6vgG11QG8" },
	{ username: "fmcmenamie1c", email: "ccanadas1c@163.com", password: "K0VXIh6bFH2" },
	{ username: "anelthrop1d", email: "dscarth1d@shutterfly.com", password: "G2BBLVNSvZ" },
];

const seedUsers = () => User.bulkCreate(userData);

module.exports = seedUsers;
